
export const travelStories = [
    {
        year: 2013,
        title: 'Baby steps',
        countries: [
            {name: 'Belgium', countryCode: 'BE'},
        ],
        introPhoto: '../Pictures/2013/hitchhiking.JPG',
        story: [
            'At the age of 21, I started out as a bike messenger, a job that would turn out to sponsor the majority of my travels. Soon after I attempted my first hitchhiking journey: from Tilburg, The Netherlands, to Ghent, Belgium, accompanied by a friend who showed me the ropes. A while after I again attempted it: I hitched my way from Breda to Brussels in Belgium with another friend.',
            'These experiences proved to be defining of my future travels, as it sparked my interest in hitchhiking and the freedom it offered.',
            'At the end of the year I grabbed my bike and cycled my way to Antwerp, Belgium and back again on the same day.',
        ],
        photos: [
            // { path: '../Pictures/2013/hitchhiking.JPG', description: 'Hitchhiking to Brussels' },
            { path: '../Pictures/2013/antwerp.JPG', description: 'Cycling to Antwerp, Belgium' },
            { path: '../Pictures/2013/land_grens.JPG', description: 'Crossing the border of The Netherlands - Belgium'}
        ],
    },
    {
        year: 2014,
        title: 'First solo journey',
        countries: [
            {name: 'Germany', countryCode: 'DE'},
            {name: 'France', countryCode: 'FR'},
            {name: 'Spain', countryCode: 'ES'},
            {name: 'Portugal', countryCode: 'PT'},
        ],
        introPhoto: '../Pictures/2014/solo_hitchhike.JPG',
        story: [
            "In the spring, I embarked on a hitchhiking adventure with another friend, journeying all the way to Hamburg. This marked the first time I spent an entire day hitchhiking.",
            "This was the year I started planning for my first big travel towards Australia and Asia",
            "During the summer months, I finally undertook a solo journey to Portugal, traversing through France and Barcelona along the way. This excursion was not only my first solo trip of multiple days but also challenged me to free camp, which was a big step out of my comfort zone.",
            "At the festival in Portugal I was attending I met my Australian friend Chris, whom I would later visit in Melbourne, Australia, and travel with throughout Australia and New Zealand.",
        ],
        photos: [
            // { path: '../Pictures/2014/solo_hitchhike.JPG', description: 'All geared up' },
            { path: '../Pictures/2014/barcelona.JPG', description: 'Barcelona, Spain' },
        ],
    },
    {
        year: 2015,
        title: 'Down under',
        countries: [
            {name: 'Australia', countryCode: 'AU'},
        ],
        introPhoto: '../Pictures/2015/gold_coast.JPG',
        story: [
            "After saving up sufficient funds, I embarked on the journey to Australia with a one-year working holiday visa in hand. Throughout the year, I experienced an incredible adventure, hitchhiking around the entire country. Along the way, I found hospitality in the homes of friendly people I met and occasionally camped out under the stars or stayed in hostels to have some rest from the road.",
            "In total, I covered 22,000 kilometers through hitchhiking alone during that year. Having done an entire loop around the continent and covering some roads criss cross. Due to the fact that I was hardly ever going to restaurants and was staying at the homes of the people I met along the way or in the homes of the friends I made along the way, I managed to sustain myself for almost the entire year without needing to work. However, towards the end of 2015, I secured a job in Perth, where I worked grueling 50-hour weeks under the scorching heat of 40 degrees Celsius. Despite the challenging conditions, it was a rewarding experience as I embraced the summer season in the southern hemisphere, working as a mover.",
        ],
        photos: [
            { path: '../Pictures/2015/brighton_beach.JPG', description: 'The colourful little beach houses of Brighton beach, Melbourne' },
            { path: '../Pictures/2015/opera_house.JPG', description: 'Sydney Opera House, Australia' },
            { path: '../Pictures/2015/gold_coast.JPG', description: 'Gold Coast sunset, Australia' },
            { path: '../Pictures/2015/litchfield.JPG', description: 'Litchfield National Park waterfall, Australia' },
            { path: '../Pictures/2015/burned_car.JPG', description: 'Burned down car along the Gibb river road, Australia' },
            { path: '../Pictures/2015/karijini.JPG', description: 'Outskirts of Karijini National Park, Australia' },
            { path: '../Pictures/2015/free_camping.JPG', description: 'Free camping somewhere in Western Australia, Australia' },
            { path: '../Pictures/2015/southwest_australia.JPG', description: 'Hitchhiking north of Perth, Australia' },
            { path: '../Pictures/2015/mount_warning.JPG', description: 'Hitchhiking towards Mount Warning to hike towards the top, Australia' },
            { path: '../Pictures/2015/south_australia.JPG', description: 'Camping somewhere in South Australia, Australia' },
            { path: '../Pictures/2015/abandoned_house.JPG', description: 'An abandoned house along the Nullabor, Australia' },
            { path: '../Pictures/2015/nullabor_cliffs.JPG', description: 'The cliffs of the Great Australian Bight, Australia' },
            { path: '../Pictures/2015/straight_road.JPG', description: 'The road along the Nullabor, Australia' },
            { path: '../Pictures/2015/sunset.JPG', description: 'Sunset along the Nullabor, Australia' },
        ],
    },
    {
        year: 2016,
        title: 'What was home like again?',
        countries: [
            {name: 'Australia', countryCode: 'AU'},
            {name: 'New Zealand', countryCode: 'NZ'},
            {name: 'Singapore', countryCode: 'SG'},
            {name: 'Thailand', countryCode: 'TH'},
            {name: 'Belgium', countryCode: 'BE'},
            {name: 'France', countryCode: 'FR'},
            {name: 'Germany', countryCode: 'DE'},
            {name: 'Poland', countryCode: 'PL'},
            {name: 'Hungary', countryCode: 'HU'},
            {name: 'Croatia', countryCode: 'HR'},
            {name: 'Montenegro', countryCode: 'ME'},
            {name: 'Albania', countryCode: 'AL'},
            {name: 'Greece', countryCode: 'GR'},
            {name: 'Turkey', countryCode: 'TR'},
            {name: 'Bulgaria', countryCode: 'BG'},
            {name: 'Serbia', countryCode: 'RS'},
        ],
        introPhoto: '../Pictures/2016/free_camp_dubrovnik.JPG',
        story: [
            "My adventure in Australia eventually drew to a close, but with the extra savings I earned from my summer job I continued my travels. I ventured to New Zealand, where over a span of six weeks, I hitchhiked 5,000 kilometers, crisscrossing throughout the South Island.",
            "When I left I visited Australia once more to visit the friends I made throughout the year there and then made my way back to The Netherlands, with a few days stop in Bangkok and Singapore.",
            "Upon returning home I picked up my old job as a bike messenger for a few months. In the summer of that year I went on a one month hitchhiking tour through Europe. The journey commenced with my father, who joined me at the age of 61, as we hitchhiked from Breda to Liège in Belgium. Continuing solo thereafter, I visited friends and family in Lyon, Krakow, and Berlin.",
            "As the year drew to a close, I grabbed my backpack again and started hitchhiking all the way to Japan. Over seven weeks, I hitchhiked through Eastern Europe, traversing countries such as Hungary, Croatia, Montenegro, Albania, Greece, and Turkey. However, unforeseen challenges, such as inadequate visa arrangements and harsh winter conditions, prompted me to alter my plans. Opting for a flight from The Netherlands, I returned home, making memorable stops in Bulgaria and Serbia along the way, and eventually reuniting with my friends and family for Christmas and New Year's Eve.",
        ],
        photos: [
            { path: '../Pictures/2016/free_camping_akaroa.JPG', description: 'View from my tent in Akaroa, New Zealand' },
            { path: '../Pictures/2016/lake_tekapo.JPG', description: 'Lake Tekapo, New Zealand' },
            // { path: '../Pictures/2016/homestay_czech.JPG', description: 'A night of drinking with my homestay, Czech Republic' },
            { path: '../Pictures/2016/free_camp_dubrovnik.JPG', description: 'Free camping outside of Dubrovnik, Croatia' },
            { path: '../Pictures/2016/butrint.JPG', description: 'View of the river at Butrint, Albania' },
            { path: '../Pictures/2016/blue_eye.JPG', description: 'Water spring the Blue Eye, Albania' },
            { path: '../Pictures/2016/gjirokaster.JPG', description: 'Gjirokaster castle, Albania' },
            { path: '../Pictures/2016/meteora.JPG', description: 'Monastaries Meteora, Greece' },
            { path: '../Pictures/2016/seven_lakes.JPG', description: 'Seven Rila Lakes, Bulgaria' },
        ]
    },
    {
        year: 2017,
        title: 'Exploring Asia',
        countries: [
            {name: 'Singapore', countryCode: 'SG'},
            {name: 'Malaysia', countryCode: 'MY'},
            {name: 'Thailand', countryCode: 'TH'},
            {name: 'Myanmar', countryCode: 'MM'},
            {name: 'Cambodia', countryCode: 'KH'},
            {name: 'Japan', countryCode: 'JP'},
            {name: 'France', countryCode: 'FR'},
        ],
        introPhoto: '../Pictures/2017/temple_japan.JPG',
        story: [
            "At the onset of the new year, I flew to Singapore to reunite with friends. Subsequently, I arranged a visa for Myanmar and hitchhiked my way there, passing through Malaysia and Thailand. This was the first time hitchhiking in a completely different culture",
            "During my four-week trip in Myanmar, hitchhiking became the main focus as it offered the highlight of my experience in the country. Unfettered by seatbelt regulations, I often found myself atop trucks, enjoying the scenic landscapes around me.",
            "Returning to Thailand, I continued my hitchhiking odyssey before pausing in Bangkok for a few days. Soon after, I ventured into Cambodia, hitchhiking around to explore it before arriving at a distant family relative I had never met before, who had been living there since 1991. I eventually concluded my time in Cambodia on the island of Koh Rong Samloem, which remains one of my favorite islands.",
            "Resuming my journey, I made my way back to Bangkok before jetting off to Japan. Over five weeks, I explored the Land of the Rising Sun, starting with a week on the island of Okinawa before taking a ferry to the mainland. Hitchhiking my way towards major cities, the initial three weeks were characterized by spontaneous camping and hitchhiking, while the latter two weeks saw me immersing myself in the vibrant cultures of Osaka, Kyoto, and Tokyo, staying with people I met through Couchsurfing or chance encounters.",
            "As the northern hemisphere summer approached, I bid farewell to Japan. Upon returning to Europe, I made quick stops in Paris and Lyon again to visit my family and friends.",
        ],
        photos: [
            { path: '../Pictures/2017/river_myanmar.JPG', description: 'Irrawaddy river, Myanmar' },
            { path: '../Pictures/2017/hitchhike_myanmar.JPG', description: 'Hitchhiking on top of a truck, Myanmar' },
            // { path: '../Pictures/2017/battambang.JPG', description: 'Hundredthousands of bats in Battambang, Cambodia' },
            { path: '../Pictures/2017/temple_japan.JPG', description: 'Temple, Japan' },
            { path: '../Pictures/2017/another_temple_japan.JPG', description: 'Another temple, Japan' },
        ]
    },
    {
        year: 2018,
        title: 'A travel reminder',
        countries: [
            {name: 'France', countryCode: 'FR'},
            {name: 'Italy', countryCode: 'IT'},
            {name: 'Slovenia', countryCode: 'SI'},
            {name: 'Croatia', countryCode: 'HR'},
            {name: 'Montenegro', countryCode: 'ME'},
            {name: 'Serbia', countryCode: 'RS'},
            {name: 'Romania', countryCode: 'RO'},
        ],
        introPhoto: '../Pictures/2018/montenegro.jpg',
        story: [
            "For the better part of the year, I settled in Breda, returning to my former job as a bike messenger. This period allowed me to replenish my savings for future travels and embrace the stability after the constant flux of life on the road.",
            "Nevertheless, the wanderlust still remained, prompting a seven-week European adventure. Hitchhiking took me to Marseille, France, where I embarked on a journey through Italy. However, Italy's strict regulations on hitchhiking along highways led me to opt for trains and buses, enabling me to explore vibrant cities like Genoa, Turin, Milan, Florence, and Venice.",
            "After traversing northern Italy, I continued my journey to Slovenia and again Croatia, retracing familiar roads from my previous travels. I rendezvoused with my family in Split and Dubrovnik, joining them on their holiday there. Subsequently, I ventured back to Montenegro and Serbia before venturing forth to Romania, where I visited the major highlights that the country has to offer.",
            "While initially considering a visit to Ukraine following my time in Romania, fatigue from constant travel set in, prompting me to make the decision to return home. Looking back at it this turned out to be a missed opportunity, due to the unfortunate war that is taking place there now.",
        ],
        photos: [
            { path: '../Pictures/2018/marseille.jpg', description: 'Frioul Islands, Marseille, France' },
            { path: '../Pictures/2018/genoa.jpg', description: 'Outskirts of Genoa, Italy' },
            { path: '../Pictures/2018/lake_bled.jpg', description: 'Lake Bled, Slovenia' },
            { path: '../Pictures/2018/plitvice.jpg', description: 'Plitvice, Croatia' },
            // { path: '../Pictures/2018/plitvice_2.jpg', description: 'Plitvice, Croatia' },
            { path: '../Pictures/2018/plitvice_3.jpg', description: 'Plitvice, Croatia' },
            // { path: '../Pictures/2018/plitvice_4.jpg', description: 'Plitvice, Croatia' },
            { path: '../Pictures/2018/dubrovnik.jpg', description: 'View of Dubrovnik from abandoned hotel, Croatia' },
            { path: '../Pictures/2018/game_of_thrones.jpg', description: 'Arena used in Game of Thrones in an abandoned hotel near Dubrovnik, Croatia' },
            { path: '../Pictures/2018/montenegro.jpg', description: 'Saints George, Montenegro' },
            { path: '../Pictures/2018/sveti_stefan.jpg', description: 'Sveti Stefan, Montenegro' },
        ]
    },
    {
        year: 2019,
        title: 'Back to Asia and Australia',
        countries: [
            {name: 'Hong Kong', countryCode: 'HK'},
            {name: 'China', countryCode: 'CN'},
            {name: 'Thailand', countryCode: 'TH'},
            {name: 'Cambodia', countryCode: 'KH'},
            {name: 'Vietnam', countryCode: 'VN'},
            {name: 'Laos', countryCode: 'LA'},
            {name: 'Malaysia', countryCode: 'MY'},
            {name: 'Singapore', countryCode: 'SG'},
            {name: 'Australia', countryCode: 'AU'},
            {name: 'New Zealand', countryCode: 'NZ'},
        ],
        introPhoto: '../Pictures/2019/koh_rong_samloem.jpg',
        story: [
            "After having been back home for a year and a half, aside of the 'short' Europe trip I made the previous year, I flew to Hong Kong. There I organized my China visa before boarding a train bound for China after a week in the city. Attempting hitchhiking in China proved to be a unique challenge unlike any other country I had visited. With most locals unfamiliar with the concept, I soon switched to buses and trains for transportation.",
            "Despite having a four-week visa, my disconnection with China led me to purchase a spontaneous ticket to Bangkok after just three weeks. After relishing the vibrant atmosphere of Bangkok, a city I have really started to love after multiple visits, I hitched my way back to Cambodia again to visit my family relative and the island of Koh Rong Samloem. Soon after I made my way to Vietnam. Hitchhiking proved difficult in Vietnam due to traveling with a companion at the time and the fact that most people ride motorbikes, thus only having a seat for one person, we resorted to buses and trains.",
            "Nearly a month was spent exploring Vietnam before venturing into Laos from the north, where hitchhiking became viable once more. Traversing the country from north to south, I occasionally rented a motorbike to navigate the scenic landscapes, an activity I enjoy even more than hitchhiking.",
            "Departing Laos, I returned to Bangkok for a brief rest stop again before hitching my way to Singapore, where I reunited with friends once again. Subsequently, I flew to Australia on a tourist visa, residing with my friend Chris in Melbourne for three months. There, I contributed to his landscaping job and received cash in hand to sustain myself.",
            "As the year drew to a close, I embarked on a journey to New Zealand with plans for a year-long working holiday visa, mirroring my experience in Australia. Similar to my time in New Zealand in 2016, I hitchhiked across the country, this time exploring the wonders of the North Island. In November, I secured a job as a construction worker in Wellington. Enjoying the city life with my income.",
        ],
        photos: [
            // { path: '../Pictures/2019/hong_kong.jpg', description: 'Skyline, Hong Kong' },
            { path: '../Pictures/2019/happy_new_year.jpg', description: 'A very Happy New Year, Guilin, China' },
            { path: '../Pictures/2019/yuangshuo.jpg', description: 'Yangshuo, China' },
            { path: '../Pictures/2019/tiger_leaping_gorge.jpg', description: 'Tiger Leaping Gorge river, China' },
            // { path: '../Pictures/2019/ladder_china.jpg', description: 'Tiger Leaping Gorge ascend from the river, China' },
            { path: '../Pictures/2019/koh_rong_samloem.jpg', description: 'Koh Rong Samloem, Cambodia' },
            { path: '../Pictures/2019/cycling_hoi_an.jpg', description: 'Cycling in Hoi An, Vietnam' },
            { path: '../Pictures/2019/hoi_an_river_selfie.jpg', description: 'Hoi An river cruise, Vietnam' },
            { path: '../Pictures/2019/boat_vietnam.jpg', description: 'Fishing out of the Chàm Islands, Vietnam' },
            // { path: '../Pictures/2019/ninh_binh.jpg', description: 'Hilltop view, Ninh Binh, Vietnam' },
            // { path: '../Pictures/2019/woman_ninh_binh.jpg', description: 'Woman posing at hilltop view, Ninh Binh, Vietnam' },
            { path: '../Pictures/2019/village_laos.jpg', description: 'A village out of Muang Ngoy, Laos' },
            // { path: '../Pictures/2019/muang_ngoy.jpg', description: 'Muang Ngoy lookout, Laos' },
            // { path: '../Pictures/2019/waterfall_laos_1.jpg', description: 'Waterfall, south of Laos' },
            // { path: '../Pictures/2019/waterfall_laos_2.jpg', description: 'Waterfall, south of Laos' },
            // { path: '../Pictures/2019/laos_monks.jpg', description: 'Monks I met at a waterfall, south of Laos' },
            { path: '../Pictures/2019/malakka.jpg', description: 'Malakka river, Malaysia' },
            // { path: '../Pictures/2019/hot_water_beach.jpg', description: 'Kawhia Hot Water Beach, New Zealand' },
        ]
    },
    {
        year: 2020,
        title: 'Disaster!',
        countries: [
            {name: 'New Zealand', countryCode: 'NZ'},
            {name: 'Australia', countryCode: 'AU'},
        ],
        introPhoto: '../Pictures/2020/akaroa_hike.jpg',
        story: [
            "At the onset of the new year, I returned to the South Island of New Zealand to explore its breathtaking landscapes and seek out new job opportunities. However, as the COVID-19 pandemic began to unfold, casting uncertainty over my plans, I decided to seek refuge at my friend in Melbourne, Australia, to assess my options.",
            "As lockdowns became imminent, I was urged to hastily book a flight back to The Netherlands, abruptly ending my travels. Upon my return home, I resumed my former role as a bike messenger, adapting to the familiar rhythm of life while reminiscing about the adventures that had come to an unexpected pause.",
            "Being landlocked I started to travel my own country a bit more, visiting places I had never seen before and going on many hikes.",
        ],
        photos: [
            { path: '../Pictures/2020/kaikoura.jpg', description: 'Kaikoura, New Zealand' },
            { path: '../Pictures/2020/akaroa_hike.jpg', description: 'Akaroa hike, New Zealand' },
            { path: '../Pictures/2020/akaroa.jpg', description: 'Hilltop view, Akaroa, New Zealand' },
            { path: '../Pictures/2020/hanmar_springs.jpg', description: 'Hilltop view, Hanmar Springs, New Zealand' },
            { path: '../Pictures/2020/landscaping.jpg', description: 'Landscaping, Melbourne, Australia' },
            { path: '../Pictures/2020/melbourne.jpg', description: 'Suburb, Melbourne, Australia' },
        ]
    },
    {
        year: 2021,
        title: 'Home is not too bad',
        countries: [
            {name: 'The Netherlands', countryCode: 'NL'},
            {name: 'Germany', countryCode: 'DE'},
            {name: 'Austria', countryCode: 'AT'},
            {name: 'Italy', countryCode: 'IT'},
            {name: 'Slovakia', countryCode: 'SK'},
            {name: 'Hungary', countryCode: 'HU'},
            {name: 'France', countryCode: 'FR'},
        ],
        introPhoto: '../Pictures/2021/smokkelroute.jpg',
        story: [
            "Due to the lockdowns and the absence of tourism, I took the opportunity to visit places in my own country like Amsterdam and Giethoorn, experiencing views that are unlikely to be seen again in the future.",
            "In the autumn of 2021, with the easing of lockdown restrictions, I embarked on a journey to reconnect with friends scattered across Europe, whom I had met during my travels or who had relocated from Breda. Hitchhiking became my mode of transport once more as I made my way to Hamburg and Innsbruck. I visited various destinations in Italy, relying on buses and trains within the country again.",
            "From Milan, I caught a flight to Vienna, and continued my expedition via buses and trains to explore Brno, Bratislava, and Budapest.",
            "Another flight took me from Budapest to Marseille. Upon arrival, I immediately hitchhiked from the airport to Montpellier and Toulouse, tracing my way back to Breda over two days.",
            "It was during this trip that I realized a shift within myself — the enchantment of hitchhiking, once so beloved, now lost its magic. Perhaps after covering over 80,000 kilometers on the road and getting older, it loses its touch.",
        ],
        photos: [
            { path: '../Pictures/2021/lockdown_amsterdam.jpg', description: 'Winter during lockdown, Amsterdam, The Netherlands' },
            { path: '../Pictures/2021/smokkelroute.jpg', description: 'Smokkelroute hike, near Breda, The Netherlands' },
            // { path: '../Pictures/2021/valkenburg.jpg', description: 'Valkenburg hike, The Netherlands' },
            // { path: '../Pictures/2021/giethoorn.jpg', description: 'Giethoorn, The Netherlands' },
            { path: '../Pictures/2021/ardenne.jpg', description: 'Ardennes, Belgium' },
            // { path: '../Pictures/2021/hitchhiking.jpg', description: 'Hitchhiking at a gasstation, The Netherlands' },
            // { path: '../Pictures/2021/camping_hitchhiking.jpg', description: 'Free camping outside of a gasstation, south of Germany' },
            { path: '../Pictures/2021/innsbruck_festival.jpg', description: 'Festival, Innsbruck, Austria' },
            // { path: '../Pictures/2021/innsbruck.jpg', description: 'Innsbruck, Austria' },
            { path: '../Pictures/2021/countryside_toulouse.jpg', description: 'Garden view of a house in the countryside outside of Toulouse, France' },
        ]
    },
    {
        year: 2022,
        title: 'Work work',
        countries: [
            {name: 'The Netherlands', countryCode: 'NL'},
            {name: 'USA', countryCode: 'US'},
            {name: 'Australia', countryCode: 'AU'},
        ],
        introPhoto: '../Pictures/2022/couch_friends.jpg',
        story: [
            "I spent 8 months working as a wheelchair mechanic, a different trade than I had ever worked before. However this job was not the trade I would want to invest more of my life in, so I used the savings for one final departure with the intend to settle down after that trip.",
            "Joined by friends I had met during my travels in Australia, we left on a two-week tour of the United States of America. Our journey took us through iconic cities like New York, New Orleans, and Los Angeles.",
            "As our American excursion came to a close, I accompanied my friends back to Australia, where I continued on my own again, visiting Melbourne and the Sunshine Coast to see my friends. This time, however, I chose the convenience of trains over the unpredictability of hitchhiking, allowing me to have plenty of time for my new hobby of reading and not having to deal with socializing or thumbing a ride.",
        ],
        photos: [
            { path: '../Pictures/2022/kinderdijk.jpg', description: 'Windmills, Kinderdijk, The Netherlands' },
            { path: '../Pictures/2022/texel.jpg', description: 'Texel, The Netherlands' },
            { path: '../Pictures/2022/pyreneeen.jpg', description: 'Pyrenees hike, France' },
            // { path: '../Pictures/2022/times_square.jpg', description: 'Times Square with my Australian friends, New York, USA' },
            // { path: '../Pictures/2022/manhattan.jpg', description: 'View of Manhattan from One World Observatory, New York, USA' },
            // { path: '../Pictures/2022/airboat.jpg', description: 'Airboat in the swamps of New Orleans, USA' },
            { path: '../Pictures/2022/couch_friends.jpg', description: 'Couch from the show intro of Friends, Warner Bros Studio, USA' },
            // { path: '../Pictures/2022/warner_bros.jpg', description: 'Famous WB tower, Warner Bros Studio, USA' },
            { path: '../Pictures/2022/sunshine_coast.jpg', description: 'Sunshine Coast, Australia' },
        ]
    },
    {
        year: 2023,
        title: 'One last time',
        countries: [
            {name: 'Australia', countryCode: 'AU'},
            {name: 'Indonesia', countryCode: 'ID'},
            {name: 'Singapore', countryCode: 'SG'},
            {name: 'Thailand', countryCode: 'TH'},
            {name: 'Germany', countryCode: 'DE'},
            {name: 'Poland', countryCode: 'PL'},
            {name: 'France', countryCode: 'FR'},
            {name: 'Hungary', countryCode: 'HU'},
        ],
        introPhoto: '../Pictures/2023/island_view.jpg',
        story: [
            "After the change of the new year, I jetted off to Perth to attend the wedding of a couple I met through a hitchhike back in 2016, shortly after my summer job there. Following the festivities, I traveled to Bali, Indonesia, seeking solitude due to a strong urge of being alone for a while so I could delve into personal projects. Immersed in video editing, devouring books, and experimenting with the programming course, which I eventually decided to focus on upon my return back home, I relished the opportunity for self-reflection and rest of my lifestyle.",
            "After three months of introspection, I resolved to pursue a career in web development. Before returning to Europe, I took two weeks to explore Bali's scenic wonders, visiting the islands around Bali such as Gili Air, Nusa Penida and others. En route home, I made a stop in my beloved city of Bangkok for two weeks before landing in Frankfurt.",
            "Aware that this journey marked the end of my nomadic lifestyle for the foreseeable future, I embarked on a heartfelt tour across Europe, reconnecting with friends and family. From vibrant cities like Cologne, Hamburg, Berlin, and Munich in Germany, to cultural gems like Krakow, Budapest, Toulouse, Montauban, and the Ardèche in France.",
            "Upon returning home in the summer, I dedicated myself to mastering programming through the 'full-stack engineer' course on Codecademy, embracing the next chapter of my journey with enthusiasm and determination.",
        ],
        photos: [
            { path: '../Pictures/2023/wedding.jpg', description: 'Wedding, Perth, Australia' },
            { path: '../Pictures/2023/margaret_river_beach.jpg', description: 'Margaret River beach, Australia' },
            // { path: '../Pictures/2023/quokka.jpg', description: 'Quoakka on Rottnest Island, Perth, Australia' },
            // { path: '../Pictures/2023/monkey_forest.jpg', description: 'Sacred Monkey Forest Sanctuary, Bali, Indonesia' },
            { path: '../Pictures/2023/romantic_beach.jpg', description: "'Romantic Beach', Pemuteran, Bali, Indonesia" },
            { path: '../Pictures/2023/jewel_singapore.jpg', description: 'Jewel Changi Airport, Singapore' },
            { path: '../Pictures/2023/skyline_singapore.jpg', description: 'Skyline, Singapore' },
            { path: '../Pictures/2023/pemuteran_mountains.jpg', description: 'Mountains, Pemuteran, Bali, Indonesia' },
            // { path: '../Pictures/2023/bali_waterfall.jpg', description: 'Waterfall, Bali, Indonesia' },
            { path: '../Pictures/2023/ogoh_ogoh.jpg', description: 'Ogoh Ogoh parade, Pemuteran, Bali, Indonesia' },
            { path: '../Pictures/2023/pemuteran.jpg', description: 'Sunset at the beach, Pemuteran, Bali, Indonesia' },
            { path: '../Pictures/2023/robot_bar.jpg', description: 'Robot Bar, Pemuteran, Bali, Indonesia' },
            // { path: '../Pictures/2023/reading.jpg', description: 'Reading a book at Robot Bar, Pemuteran, Bali, Indonesia' },
            // { path: '../Pictures/2023/palmtrees.jpg', description: 'Palmtrees, Gili Air, Indonesia' },
            { path: '../Pictures/2023/gili_meno.jpg', description: 'Gili Meno, Indonesia' },
            { path: '../Pictures/2023/island_view.jpg', description: 'View of Gili Trawangan, Indonesia' },
            { path: '../Pictures/2023/sunset_gili_air.jpg', description: 'Sunset at the beach, Gili Air, Indonesia' },
            { path: '../Pictures/2023/beetle.jpg', description: 'Abandoned Volkswagen Beetle, Bangkok, Thailand' },
            { path: '../Pictures/2023/overgrown_jungle.jpg', description: 'Cycling through the city jungle, Bangkok, Thailand' },
            // { path: '../Pictures/2023/krakow.jpg', description: "St. Mary's Basilica, Krakow, Poland" },
            { path: '../Pictures/2023/bremen_village.jpg', description: 'House of a friend in a village outside of Bremen, Germany' },
            { path: '../Pictures/2023/lauzerte.jpg', description: 'Lauzerte, France' },
            // { path: '../Pictures/2023/boldogko_castle.jpg', description: 'Boldogkő castle, Hungary' },
        ]
    },
    {
        year: '?',
        title: 'Next stop',
        countries: [
            {name: '???', countryCode: ''},
        ],
        introPhoto: '../Pictures/2024/looking_ahead.jpg',
        story: [
            "As I transition towards a more settled phase of building my career, my future travelplans are uncertain. My primary objective for the forthcoming years is to amass knowledge and experience within the field of software engineering, aspiring to become a proficient expert. With time, I might aim to leverage my accumulated knowledge and skills to transition into freelancing, unlocking doors to new business ventures.",
        ],
        photos: [
        ]
    },
]